### ISSUE TITLE
inspect.getargspec vs inspect.getfullargspec?

### ISSUE THREAD

**Issue by fpemud** [Friz-zy/pyspaces#3]
```
fpemud@l02107b ~/workspace/strict_pgs $ space execute -v --pid --mnt --user --uid 1000 --gid 1000 bash -c 'mount -t proc /proc; ps ax'
Traceback (most recent call last):
  File "/usr/bin/space", line 9, in <module>
    load_entry_point('pyspaces==1.4', 'console_scripts', 'space')()
  File "/usr/lib64/python3.3/site-packages/pyspaces/cli.py", line 133, in cli
    args.func(args, extra)
  File "/usr/lib64/python3.3/site-packages/pyspaces/cli.py", line 152, in execute
    all=args.all
  File "/usr/lib64/python3.3/site-packages/pyspaces/process.py", line 188, in __init__
    for k in getargspec(Process.__init__).args:
  File "/usr/lib64/python3.3/inspect.py", line 826, in getargspec
    raise ValueError("Function has keyword-only arguments or annotations"
ValueError: Function has keyword-only arguments or annotations, use getfullargspec() API which can support them
```

The error disappears after I change getargspec to getfullargspec.
Is it a bug? Should I submit a pull request?

**Comment by Friz-zy** [comment]
Hi, thanks for report.
I didn't checked pyspaces with latest python 3.

You PR is welcome, just check that it will work for both 2 and 3 versions.
Or I'll take a look later myself.

**Comment by Friz-zy** [comment]
Thanks a lot, v1.4.1 created and uploaded into PYPI
